#!/bin/sh

post_install() {
  # Update desktop database and icon cache
  update-desktop-database >/dev/null 2>&1 || true
  gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor >/dev/null 2>&1 || true
}

post_upgrade() {
  post_install
}

pre_remove() {
  # update caches after remove
  update-desktop-database >/dev/null 2>&1 || true
  gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor >/dev/null 2>&1 || true
}
